### ISSUE TITLE
Fluent Dart - Plasma Theme - small improvements

### ISSUE THREAD

**Issue by psifidotos** [vinceliuice/Fluent-kde#1]
really nice!
there are some things that need improvement and you can check them out with Latte Dock settings window in advanced mode that is a full preview of your entire plasma theme components.

Fluent Dark theme:
1. The analog clock needs more contrast
2. The Switch button can not indicate visually when it is active or not, maybe the same color with Checked buttons should be used and its inactive should have an inactive colorness
3. The Sliders maybe they need a little smaller circle

![εικόνα](https://user-images.githubusercontent.com/2216474/113262360-2fa78b80-92d9-11eb-9ec7-87ed6dd0e4b2.png)

**Comment by vinceliuice** [comment]
The Switch button can not improvement, because plasma don't have any switch button, so latte use normal button to style switch,I can't do anything about this!

**Comment by psifidotos** [comment]
> The Switch button can not improvement, because plasma don't have any switch button, so latte use normal button to style switch,I can't do anything about this!

yes it can, for plasma themes there is **widgets/slider.svgz** that can be used like oxygen plasma theme is already providing.

The Latte Switch button is drawn by the following plasma themes components that are already provided. From my testing Oxygen plasma theme provides the best Switch contrast example and includes a **widgets/slider.svgz** file

https://invent.kde.org/plasma/latte-dock/-/blob/master/declarativeimports/components/private/SwitchStyle.qml

**Comment by psifidotos** [comment]
![εικόνα](https://user-images.githubusercontent.com/2216474/113273654-8adf7b00-92e5-11eb-84ed-0434acf4b8da.png)

**Comment by vinceliuice** [comment]
But if I changed the slider and button style, all button and slide of plasma will changed, This will lead to bad styles in many places
