### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by narisuzu** [vinceliuice/Fluent-kde#11]
I know my question is stupid, but is it possible to make rounded corner in the bottom of windows in KDE without a thick border? Just like MacOS/Windows 11 or some theme in AwesomeWM. to cut the window bottom corners directly instead of adding a bottom border with rounded corners

**Comment by vinceliuice** [comment]
https://github.com/cutefishos/kwin-plugins

**Comment by vinceliuice** [comment]
I only find this, but it works not so perfect on other aurorae theme

**Comment by vinceliuice** [comment]
I hope someone can make a plugin for normal kde plasma desktop

**Comment by narisuzu** [comment]
thanks for reply
