### ISSUE TITLE
Teal theme color variant

### ISSUE THREAD

**Issue by jarjut** [vinceliuice/Fluent-kde#18]
it would be nice if you added a teal color variant such as the gtk version. 

Thanks for creating such an awesome theme

**Comment by vinceliuice** [comment]
No problem!

**Comment by tsbarnes** [comment]
Just wanted to second this, I love the teal version because it goes so well with Manjaro, and I'd love to be able to use it on Manjaro KDE.

**Comment by xelser** [comment]
bump
