### ISSUE TITLE
Adaptive transparency is not working

### ISSUE THREAD

**Issue by prateekmedia** [vinceliuice/Fluent-kde#20]
![image](https://user-images.githubusercontent.com/41370460/142727199-6d3b80f6-1fde-4229-a777-55bc0576aa58.png)

That is not transparent!

**Comment by vinceliuice** [comment]
Are you using the solid version?

**Comment by vinceliuice** [comment]
I don't have this issue, download the last update on github and try ./install.sh --round again

**Comment by prateekmedia** [comment]
Ok wait

**Comment by prateekmedia** [comment]
No, same behaviour :(

Fluent
![image](https://user-images.githubusercontent.com/41370460/142727711-f09bd4c8-9f80-437e-aec7-f01b9fa727db.png)

Orchis
![image](https://user-images.githubusercontent.com/41370460/142727731-6b0c66e7-8fae-46e2-9bd5-221c171db4e2.png)

**Comment by prateekmedia** [comment]
My KDE version is 5.23.3.

**Comment by prateekmedia** [comment]
I think #19 is related.

**Comment by vinceliuice** [comment]
![Screenshot_20211120_212903](https://user-images.githubusercontent.com/7604295/142728259-811da9a4-12a8-477a-a07a-f0695140a8ab.png)

**Comment by vinceliuice** [comment]
Disable this option

**Comment by vinceliuice** [comment]
Or download the last update I just upload
