### ISSUE TITLE
Make a option to get the Windows 11-like task manager (window switcher) style

### ISSUE THREAD

**Issue by nguyensang28** [vinceliuice/Fluent-kde#25]
I mean something similar to that:
![IMG_20220223_143334](https://user-images.githubusercontent.com/85934291/155277585-930ac12a-e813-441b-8aa6-076d93976012.png)
![c05b82e3-6dbf-4069-9160-4879c87a5b1b](https://user-images.githubusercontent.com/85934291/155278072-831e0866-96e4-4189-86ba-5c92d9437047.png)
![taskbar-button-glow_(1)_1628069656772_1628069680564](https://user-images.githubusercontent.com/85934291/155278116-0c058fd5-aad7-4ac4-b710-6ac2d98f4c28.png)
![126225039-a523a3a7-b5c3-446e-8644-4e59fd1f0530](https://user-images.githubusercontent.com/85934291/155278557-0fe4b564-718b-49d5-bbbd-703b6608c6ac.png)
There's a theme that implemented this similar style (just for reference)
https://github.com/yeyushengfan258/Win11OS-kde

**Comment by vinceliuice** [comment]
Fixed now!
