### ISSUE TITLE
window border setting, "no borders" doesn't work with fluent round

### ISSUE THREAD

**Issue by gerblesh** [vinceliuice/Fluent-kde#28]
![image](https://user-images.githubusercontent.com/101901964/171768466-4ab992ff-87f9-491d-b849-9448e9d463f6.png)
using lightly shaders for the window outline and when using fluent round I noticed that the noborders option doesn't seem to work for the bottom border on fluent round. It works for the normal fluent but not fluent round. Main reason I use fluent round is for the blurred top bar.

**Comment by gazsp** [comment]
Same here.

**Comment by vinceliuice** [comment]
Added normal version (without bottom rounded corner)
