### ISSUE TITLE
Show Desktop (Win7) - Unsupported Widget Plasma 6

### ISSUE THREAD

**Issue by niri-san** [vinceliuice/Fluent-kde#44]
Hello, widget Show Desktop (Win7) / org.kde.plasma.win7showdesktop shown as unsupported on Plasma 6 and cannot be set on taskbar.

![Screenshot_20240621_065838](https://github.com/vinceliuice/Fluent-kde/assets/160327855/69de64cd-15db-43b8-82c1-257e78758419)

```
Operating System: openSUSE Tumbleweed 20240619
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Graphics Platform: Wayland
```

**Comment by vinceliuice** [comment]
Install plasma 6 version here: https://store.kde.org/p/2151247/
