### ISSUE TITLE
SDDM 出bug炸了

### ISSUE THREAD

**Issue by 1900011604** [vinceliuice/Fluent-kde#7]
![3](https://user-images.githubusercontent.com/65082432/124372208-c2323f00-dcbb-11eb-8073-ffca4393fd46.jpg)

前几天重装了win11，才在manjaro上装的，通过官方下载器（系统设置）下载，出了这个问题

**Comment by vinceliuice** [comment]
你的plasma桌面版本是多少啊

**Comment by vinceliuice** [comment]
没早点发现这个问题， 现在修复了

**Comment by vinceliuice** [comment]
你可以在这里下载进 sddm运行 `sudo ./install.sh`
